repos:
  # - repo: https://github.com/terraform-docs/terraform-docs
  #   rev: "v0.19.0"
  #   hooks:
  #     - id: terraform-docs-go
  #       args: ["markdown", "table", "--output-file", "README.md", "./terraform"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.96.1"
    hooks:
      - id: terraform_fmt
        files: terraform
      # - id: terraform_validate
      #   files: terraform
      # - id: terraform_tflint
      #   files: terraform
      # - id: terraform_tfsec
      #   files: terraform
